I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 28, in script call
    call sayori_date from _call_sayori_date
  File "game/date.rpy", line 1364, in script
    show shardb at glass(x=10, t=2)
  File "game/date.rpy", line 1364, in <module>
    show shardb at glass(x=10, t=2)
TypeError: 'bool' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 28, in script call
    call sayori_date from _call_sayori_date
  File "game/date.rpy", line 1364, in script
    show shardb at glass(x=10, t=2)
  File "C:\Users\Declan\Downloads\dmodding\renpy-7.3.5-sdk\renpy\ast.py", line 1183, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Declan\Downloads\dmodding\renpy-7.3.5-sdk\renpy\ast.py", line 1142, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Users\Declan\Downloads\dmodding\renpy-7.3.5-sdk\renpy\python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Declan\Downloads\dmodding\renpy-7.3.5-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/date.rpy", line 1364, in <module>
    show shardb at glass(x=10, t=2)
TypeError: 'bool' object is not callable

Windows-8-6.2.9200
Ren'Py 7.3.5.606
A Date With Sayori 1.1.0
Mon Jun 21 15:10:57 2021
